### ISSUE TITLE
how to use swagger authentication?

### ISSUE THREAD

**Issue by JugnuPathak** [cdimascio/generator-express-no-stress#11]
I'm new to node and swagger. Can you please guide me how to implement jwt token authentication in current architecture?

**Comment by cdimascio** [comment]
You can certainly add jwt based authentication to a project scaffolded by generator-express-no-stress. We have no strong opinion with respect to how you go about that.

Here are some tips:
- See https://swagger.io/docs/specification/2-0/authentication/ to integrate authentication into the Swagger spec. see`Api.yaml` in this project.
- With respect to jwt based authentication, you may want to consider a library like https://github.com/auth0/express-jwt, https://github.com/auth0/node-jsonwebtoken, or http://www.passportjs.org/

**Comment by JugnuPathak** [comment]
@cdimascio  Thanks for help. OK, So by defining `securityDefinitions` and `security` in Api.yaml we are just creating swagger UI for authentication/authorization and passing token and key while try it. But to implement my business logic for authentication/authorization, I might need to use any express middle ware like passport or library you have suggested?

**Comment by cdimascio** [comment]
You got it. Good luck!

**Comment by JugnuPathak** [comment]
@cdimascio  Ok I got it and its working. I think right now its using swagger 2.0. Will we have any release for  open api 3 (swagger 3.0.0) specifications?
