### ISSUE TITLE
OpenAPI 3.0 Support

### ISSUE THREAD

**Issue by kaufmann42** [cdimascio/generator-express-no-stress#14]
Hey there,

Is there any future for 3.x support? Thanks!

**Comment by cdimascio** [comment]
There is a plan to support this. ETA not available yet

**Comment by mlasak** [comment]
I guess this is the blocker, isn't it?
https://github.com/APIDevTools/swagger-express-middleware/issues/81

**Comment by cdimascio** [comment]
that's right. if you know of similar alternatives, i'm open to potentially swapping out that middleware

**Comment by cdimascio** [comment]
@kaufmann42 @mlasak Given that swagger-express-middleware has been slow to adopt openapi3, i've decide to start work on a a new openapi validation middleware library, [express-openapi-validator](https://github.com/cdimascio/express-openapi-validator).

It's currently in alpha. If you're interested in kicking the tires or contributing I'd would certainly welcome it. 

I've also putting together a very simple sample project,  [express-openapi-validator-example](https://github.com/cdimascio/express-openapi-validator-example) as a basic demonstration. 

Ultimately, my goal is to integrate this library into generator-express-no-stress for folks who choose to use openapi3. Before I do that, I certainly want to ensure that the library is battle tested (or at least an optional choice)

In any case, I can certainly use help with testing and I certainly welcome contributions

**Comment by cdimascio** [comment]
openapi 3.x support is now available in v7.0.1
