### ISSUE TITLE
[Question] How to add more input validation ?

### ISSUE THREAD

**Issue by mandarvaze** [cdimascio/generator-express-no-stress#19]
OpenAPI 3.0 allows to define additional data called `format` when specifying the parameters, see [here](https://swagger.io/docs/specification/data-models/data-types/#string)
This allows to provide additional validation like `isDate`, `isUUID` etc.

I understand that the project supports only swagger 2.0 spec.

So my question is : What is the "elegant" way to add my own "input data validations" as explained above ? 
I can always validate inside the controller, but that seems crude, and lot of code may be repeated.

**Comment by cdimascio** [comment]
@mandarvaze you can use Data Types along with patterns, minimum, maximum, etc
An example of a regex pattern might be
   `pattern: ^([a-f\d]{24},?)+$`
You can view the swagger 2.0 spec [here](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md):

**Comment by cdimascio** [comment]
@mandarvaze closing this out, please reopen if needed
