### ISSUE TITLE
WebStorm Configuration?

### ISSUE THREAD

**Issue by sns45** [cdimascio/generator-express-no-stress#20]
I am not able to attach debugger with ES6 and hot reloads in WebStorm.
Let me know your web storm config which works for you. Thanks.

**Comment by cdimascio** [comment]
@sns45 This project utlizes the standard [Inspector Protocol](https://chromedevtools.github.io/debugger-protocol-viewer/v8/) for v8.

Please have a look at the following [doc](https://nodejs.org/en/docs/guides/debugging-getting-started/) for details. It includes some basic instruction for Webstorm.

Note, if you do get this working, I would very much appreciate it if you could provide those steps here or better yet, submit a PR. It would be fantastic to have this information available in the [README](https://github.com/cdimascio/generator-express-no-stress/blob/master/README.md). I'm sure others are interested.

 I have provided an [example launch configuration](https://github.com/cdimascio/generator-express-no-stress/blob/master/assets/.vscode/launch.json) to set up debugging in VSCode. It may prove useful when setting it up Webstorm

**Comment by lwf804** [comment]
- Run this script: `"dev:debug": "nodemon server --exec babel-node --config .nodemonrc.json --inspect | pino-pretty",`

- Then add config to webStorm: `Attach to Node.js/Chrome` with port `9229`. After press debug button!

**Comment by cdimascio** [comment]
@lwf804 Thanks for the tips. Would you mind providng some additional detail around _add config to WebStorm_. I'd like to post this onto the README

**Comment by cdimascio** [comment]
This ticket is labeled for Hacktoberfest. 
We are looking for documentation to describe how to configure Webstorm to debug the generated project.

The README already contains documentation describing how to set up debugging using VSCode. This issue asks that doc is also provided to describe how to set up debugging using Webstorm.
