### ISSUE TITLE
Update pino to express-pino-logger or pino-pretty

### ISSUE THREAD

**Issue by sns45** [cdimascio/generator-express-no-stress#21]
Pino's CLI documentation is not good. It's unclear what` pino -o` does.
It's better to use something else or change the package to express-pino-logger with the new pino pretty logger.

**Comment by cdimascio** [comment]
Thanks for the heads up. I plan to get this in soon

**Comment by cdimascio** [comment]
@sns45 [Release 5.0.0](https://github.com/cdimascio/generator-express-no-stress/releases/tag/v5.0.0) contains a number of updates including the upgrade of pino. As part of this upgarde pino-pretty is used to prettify pino logs.

**Comment by cdimascio** [comment]
fixed in 5.0.0
