### ISSUE TITLE
How can I change sourceroot of babel .?

### ISSUE THREAD

**Issue by simon0210** [cdimascio/generator-express-no-stress#24]
when I start express server using 'npm run dev' command

It seems to use server/index.js as the source root.

How can I see that configuration.?

**Comment by cdimascio** [comment]
The `server` directory is specified in the `dev` script target defined `package.json`

Note, `server` below:
```
dev": "nodemon server --exec babel-node --config .nodemonrc.json | pino-pretty",
```
