### ISSUE TITLE
how to use with own api yaml definition

### ISSUE THREAD

**Issue by semsitivity** [cdimascio/generator-express-no-stress#3]
Hi,
I don't really get it. Is this tool can be used with any swagger 2 yaml definition and does it generate controller and router stub according to it or is this just a sample of good practice for api validation and documentation hosting hosted in a nice way with express.
In any case, this is really a nice work.
Br,

**Comment by cdimascio** [comment]
@semsitivity This project is a [Yeoman](http://yeoman.io/) generator for Node.js API and web applications. It enables developers to scaffold a a 12-factor compatible api / web application complete with structured logging, api validation, interactive documentation, es.next, etc. express-not-stress is a project generator not a swagger code generator. You can absolutely use an existing swagger definition with express-no-stress. You, however provide the implementation (write it yourself, use a 3rd party code generator... thats up to you - express-no-stress is not opinionated in this regard).
