### ISSUE TITLE
Application at elasticbeanstalk aws

### ISSUE THREAD

**Issue by XyDahn** [cdimascio/generator-express-no-stress#31]
Hi, Whats up?

Well, Is possible publish application generation for generator-express-no-stress at AWS elasticbeanstalk? 

Thanks

**Comment by XyDahn** [comment]
Create file: 
### /.ebextensions/nodecommand.config
`option_settings: 
  aws:elasticbeanstalk:container:nodejs: 
    NodeCommand: "node dist/index.js"
`

Create file bash:
### deploy-aws.sh
`#!/bin/bash
npm run compile && zip -r partner-api.zip README.md package.json public server test .ebextensions dist
`

**Comment by cdimascio** [comment]
Hi @XyDahn sounds like you'e got a reasonable solution! thanks for the ticket
