### ISSUE TITLE
--docker option - inverse behaviour

### ISSUE THREAD

**Issue by zijua** [cdimascio/generator-express-no-stress#33]
When running

`yo express-no-stress myapp`

Docker files are copied.

When running

`yo express-no-stress myapp --docker`

Docker files are ignored.

This seems to be the opposite than the doc specification "Install Docker artifacts including a Dockerfile" inside Usage CLI section of the README.

This should be confirmed by the lines inside app/index.js

```

if (this.docker) {
          copyOpts.globOptions.ignore.push('**/+(Dockerfile|.dockerignore)');
}
```

**Comment by cdimascio** [comment]
Thanks @zijua. This now fixed in `7.1.2`
