### ISSUE TITLE
Test teardown?

### ISSUE THREAD

**Issue by dels07** [cdimascio/generator-express-no-stress#36]
Hi,

Currently I use ava & supertest for controller/endpoint testing, so far I having problem with test being successful but I keep getting uncaught exception, also running several tests together spawn the same error.

My understanding is that supertest tried to re-initiate Server class which found in `server/index.js` via `request(Server)` everytime it's running the tests.

I tried to shutdown server by adding method to call `app.close()` in `server.js` but `close()` doesn't recognize as known function, something like:

```
export default class ExpressServer { 
    ...
    close() {
        app.close()
    }
}
```

```
// ava
test.after(() => {
    Server.close() // or Server.app.close() return undefined
})
```

**Comment by cdimascio** [comment]
@dels07 Thanks for you interest in express-no-stress. This question is related to express and supertest. you may want to try this question on StackOverflow. best
