### ISSUE TITLE
Event Exit

### ISSUE THREAD

**Issue by santhosekumar19** [cdimascio/generator-express-no-stress#37]
generator-express-no-stress\app\templates\test\examples.controller.js

**Comment by cdimascio** [comment]
Thanks for the issue, @santhosekumar19.
Would you mind providing some additional details, so that I can reproduce.

**Comment by santhosekumar19** [comment]
i have fixed it, by reinstalling yo and express-generator, it now working fine, thanks for the swift response

**Comment by cdimascio** [comment]
Excellent! Glad you have it working
