### ISSUE TITLE
add default bodyparser for text and urlencoding

### ISSUE THREAD

**Issue by cdimascio** [cdimascio/generator-express-no-stress#38]
Add a bodyparser for text to server.js
https://github.com/cdimascio/generator-express-no-stress/blob/master/app/templates/server/common/server.js#L21

**Comment by frankcalise** [comment]
What options do you want to support here, just limit for now?

**Comment by cdimascio** [comment]
Just limit is good for now.

**Comment by cdimascio** [comment]
available in v8.5.2
