### ISSUE TITLE
Question: how to deploy

### ISSUE THREAD

**Issue by jacobwod** [cdimascio/generator-express-no-stress#57]
I'm just wondering what's the best practice for deploying to my local production server? (I plan on running the app with PM2 later on.)

I've built the project with `npm run compile` which got me the `dist` directory. I've copied `dist` to my server and expected to start with `node dist/index.js`, but ran into problems:
```
internal/modules/cjs/loader.js:969
  throw err;
  ^

Error: Cannot find module 'dotenv'
Require stack:
[......]
}
```

Sure enough, no modules seem to have made it past the compile stage, so I guess I'm not deploying correctly. Any ideas?

**Comment by cdimascio** [comment]
To run the production build. First build via `npm run compile`.

Run `npm start` to run the production build

**Comment by cdimascio** [comment]
Note that dist contains the server transpiled js, however that's not quite enough. You still need public/ package.json, and to run npm install to install the dependencies

Coming from the other side, you can exclude server/ and test/ and some of the config files

**Comment by jacobwod** [comment]
Thanks, will take a look into this. Sounds reasonable.
