### ISSUE TITLE
Missing directory separator when setting appPath

### ISSUE THREAD

**Issue by jacobwod** [cdimascio/generator-express-no-stress#60]
I belive there might be a missing slash (or back-slash, depending on the OS) on the following line:
https://github.com/cdimascio/generator-express-no-stress/blob/53082f95d018be189a5e0e4ae3f903e77cdaefb1/app/templates/server/common/server.js#L25

Some logging makes it more clear:
```
[2020-11-30T09:53:12.925] [DEBUG] hajk - __dirname:  /Users/me/dev/hajk-backend/server/common
[2020-11-30T09:53:12.925] [DEBUG] hajk - root:  /Users/me/dev/hajk-backend
[2020-11-30T09:53:12.925] [DEBUG] hajk - appPath:  /Users/me/dev/hajk-backendclient
```

I'm not entirely sure why we do `app.set('appPath')` in the first place, as I can't find it being used anywhere, nor do I have a `client` directory anywhere in my project. 

But either way, **I assume the correct value of the last debug line should be `/Users/me/dev/hajk-backend/client` and not `/Users/me/dev/hajk-backendclient`**. It could be acomplished with `path.join()` to ensure OS-agnostic path separators:

```javascript
app.set("appPath", path.join(root, "client"));
```

**Comment by cdimascio** [comment]
@jacobwod, Good find. This is unnecessary and can be removed entirely. Feel free to submit a PR to remove it.
